# Generated by Django 3.1.5 on 2021-01-27 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_superuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
