# Generated by Django 3.1.5 on 2021-01-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='ids',
            new_name='uuid',
        ),
    ]
